/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import BookingManagement.*;
import BusManagement.*;
import RegistryManagement.*;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Sian Paul Lasaga
 */
public class AddTripFrame extends javax.swing.JFrame {

    private BusCompany busCo = BusCompany.getInstance();
    private Trip trip = new Trip();
    private SearchEngine search = new SearchEngine();
    private Registry reg = Registry.getInstance();
    private static CodeGenerator gen = CodeGenerator.getInstance();
    private JTextField locationFromText;
    private JTextField locationToText;
    private JTextField venueText;
    private Vector<String> busNumbers=new Vector<String>();
    /**
     * Creates new form AddTripFrame
     */
    public AddTripFrame() {
        initComponents();
        for (Bus bus : busCo.getBusses()) {
            busNumbers.add(bus.getBusNumber());
        }
        busNoCBox.setModel(new DefaultComboBoxModel(busNumbers));
        updateTripButton.setEnabled(false);
        yearCBox.setModel(new DefaultComboBoxModel());
        for (int i = 2015; i <= 2020; i++) {
            yearCBox.addItem(i);
        }
        busNoCBox.setModel(new DefaultComboBoxModel());
        for (Bus bus : busCo.getBusses()) {
            busNoCBox.addItem(bus.getBusNumber());
        }
        ReferenceNoLabel.setText(CodeGenerator.generateReferenceNumber());
        locationFromText = (JTextField) locationFromComboBox.getEditor().getEditorComponent();
        locationToText = (JTextField) locationToComboBox.getEditor().getEditorComponent();
        venueText = (JTextField) tripVenueComboBox.getEditor().getEditorComponent();
    
//        routeText.addKeyListener(new KeyAdapter() {
//            public void keyTyped(KeyEvent e){
//                EventQueue.invokeLater(new Runnable(){
//                    @Override
//                    public void run() {
//                        String text = routeText.getText();
//                        if(text.length() == 0){
//                            routeText.hidePopup();
//                        }
//                    }
//                    
//                });
//            }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewTripsButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        AddTripButton = new javax.swing.JButton();
        ViewTripsButton = new javax.swing.JButton();
        busNoCBox = new javax.swing.JComboBox();
        monthLabel = new javax.swing.JLabel();
        monthCBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        dayCBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        yearCBox = new javax.swing.JComboBox();
        timeText = new javax.swing.JFormattedTextField();
        backButton = new javax.swing.JButton();
        ReferenceNoLabel = new javax.swing.JLabel();
        updateTripButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        locationFromComboBox = new javax.swing.JComboBox();
        locationToComboBox = new javax.swing.JComboBox();
        tripVenueComboBox = new javax.swing.JComboBox();

        ViewTripsButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ViewTripsButton1.setText("View Trips");
        ViewTripsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTripsButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trip Menu"));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Date:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Bus No.:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Time:");

        jLabel3.setText("Reference No.");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Price:");

        AddTripButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AddTripButton.setText("Add Trip");
        AddTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTripButtonActionPerformed(evt);
            }
        });

        ViewTripsButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ViewTripsButton.setText("View Trips");
        ViewTripsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTripsButtonActionPerformed(evt);
            }
        });

        busNoCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        busNoCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNoCBoxActionPerformed(evt);
            }
        });

        monthLabel.setText("Month:");

        monthCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        monthCBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthCBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monthCBoxMouseEntered(evt);
            }
        });

        jLabel7.setText("Day:");

        dayCBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayCBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dayCBoxMouseEntered(evt);
            }
        });

        jLabel8.setText("Year:");

        yearCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearCBoxActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        ReferenceNoLabel.setText("#######");

        updateTripButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        updateTripButton.setText("Update Trip");
        updateTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTripButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Trip Venue:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Route"));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("From:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("To:");

        locationFromComboBox.setEditable(true);

        locationToComboBox.setEditable(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(locationFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tripVenueComboBox.setEditable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(monthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel2))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(busNoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tripVenueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(backButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewTripsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateTripButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                                .addComponent(AddTripButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ReferenceNoLabel))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ReferenceNoLabel))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(monthLabel)
                    .addComponent(monthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busNoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tripVenueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addComponent(AddTripButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateTripButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewTripsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        //dayCBox.setModel(new DefaultComboBoxModel());
        //try{
            //if(monthCBox.getSelectedItem().toString().equals("Feb")){
                //    for(int i = 1; i<=29; i++){
                    //        monthCBox.addItem(i);
                    //    }
                //}
            //}
        //catch(Exception e){
            ////}
        //}

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadData(Trip trip){
        updateTripButton.setEnabled(true);
        AddTripButton.setEnabled(false);
        ViewTripsButton.setEnabled(false);
        ReferenceNoLabel.setText(trip.getReferenceNo());
        locationFromText.setText(trip.getTripFrom());
        locationToText.setText(trip.getTripTo());
        busNoCBox.setSelectedItem(trip.getBus().getBusNumber());
        monthCBox.setSelectedIndex(trip.getSchedule().getMonth()+1);
        for (int i = 1; i <= 31; i++) {
            dayCBox.addItem(i);
        }
        dayCBox.setSelectedIndex(trip.getSchedule().getDate()-1);
        yearCBox.setSelectedIndex(trip.getSchedule().getYear()-115);
        timeText.setText(trip.getSchedule().getHours()+":"+trip.getSchedule().getMinutes());
        venueText.setText(trip.getVenue());
        priceText.setText(trip.getPrice()+"");
        this.trip = trip;
        
    }
    
    private void ViewTripsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTripsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTripsButton1ActionPerformed

    private void updateTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTripButtonActionPerformed
        // TODO add your handling code here:
        if(locationFromText.getText().isEmpty() || locationToText.getText().isEmpty() || busNoCBox.getSelectedItem().toString().isEmpty() || monthCBox.getSelectedIndex() == 0
            || dayCBox.getSelectedItem().toString().isEmpty() || timeText.getText().isEmpty() || priceText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the data.", "Not complete!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String locationFrom = locationFromText.getText();
            String locationTo = locationToText.getText();
            String time = timeText.getText();
            String date = (int)(monthCBox.getSelectedIndex())+"/"+dayCBox.getSelectedItem().toString()+"/"+(int)(yearCBox.getSelectedIndex()+15);
            String busNo = busNoCBox.getSelectedItem().toString();
            Bus bus = search.searchBusByBusNo(busNo);      
            String venue = venueText.getText();
            String referenceNo = ReferenceNoLabel.getText();
            double price = Double.parseDouble(priceText.getText());
            trip.setTripFrom(locationFrom);
            trip.setTripTo(locationTo);
            trip.setBus(bus);
            trip.setSchedule(new Date(date+" "+time));
            trip.setVenue(venue);
            trip.setReferenceNo(referenceNo);
            trip.setPrice(price);
            reg.addTrip(trip);
            reg.removeTrip(trip);
            reg.addTrip(trip);
            JOptionPane.showMessageDialog(null, "The trip has been updated", "Finished", JOptionPane.INFORMATION_MESSAGE);
            this.hide();
            new ViewTripMenu().show();
        }
    }//GEN-LAST:event_updateTripButtonActionPerformed

    private void yearCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearCBoxActionPerformed

    private void dayCBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayCBoxMouseEntered
        // TODO add your handling code here:
        dayCBox.setModel(new DefaultComboBoxModel());
        String month = null;
        month = monthCBox.getSelectedItem().toString();
        if(month.equals("Feb")){
            for (int i = 1; i < 30; i++) {
                dayCBox.addItem(i);
            }
        }
        if(month.equals("Jan")||month.equals("Mar")||month.equals("May")||month.equals("Jul")
            ||month.equals("Aug")||month.equals("Oct")||month.equals("Dec")){
            for (int i = 1; i < 32; i++) {
                dayCBox.addItem(i);
            }
        }
        if(month.equals("Apr")||month.equals("Jun")||month.equals("Sep")||month.equals("Oct")
            ||month.equals("Nov")){
            for (int i = 1; i < 31; i++) {
                dayCBox.addItem(i);
            }
        }
    }//GEN-LAST:event_dayCBoxMouseEntered

    private void dayCBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayCBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dayCBoxMouseClicked

    private void monthCBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthCBoxMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_monthCBoxMouseEntered

    /*Mouse events bellow are empty(Cannot be deleted)*/
    private void monthCBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthCBoxMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_monthCBoxMouseClicked

    private void busNoCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNoCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busNoCBoxActionPerformed

    private void ViewTripsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTripsButtonActionPerformed
        // TODO add your handling code here:
        ViewTripMenu view = new ViewTripMenu();
        view.show();
    }//GEN-LAST:event_ViewTripsButtonActionPerformed

    private void AddTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTripButtonActionPerformed
        // TODO add your handling code here:
        if(locationFromText.getText().isEmpty() || locationToText.getText().isEmpty() || busNoCBox.getSelectedItem().toString().isEmpty() || monthCBox.getSelectedIndex() == 0
            || dayCBox.getSelectedItem().toString().isEmpty() || timeText.getText().isEmpty() || priceText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the data.", "Not complete!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String locationFrom = locationFromText.getText();
            String locationTo = locationToText.getText();
            String time = timeText.getText();
            String date = (int)(monthCBox.getSelectedIndex())+"/"+dayCBox.getSelectedItem().toString()+"/"+(int)(yearCBox.getSelectedIndex()+15);
            String busNo = busNoCBox.getSelectedItem().toString();
            Bus bus = search.searchBusByBusNo(busNo);      
            String venue = venueText.getText();
            String referenceNo = ReferenceNoLabel.getText();
            double price = Double.parseDouble(priceText.getText());
            trip = new Trip(TripStatus.READY, price, locationFrom, locationTo, bus, new Date(date+" "+time), referenceNo, venue);
            reg.addTrip(trip);
            JOptionPane.showMessageDialog(null, "The trip has been added", "Finished", JOptionPane.INFORMATION_MESSAGE);
            this.hide();
            new AddTripFrame().show();
        }

    }//GEN-LAST:event_AddTripButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hide();
        MainMenu mainMenu=new MainMenu();
        mainMenu.show();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTripFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTripButton;
    private javax.swing.JLabel ReferenceNoLabel;
    private javax.swing.JButton ViewTripsButton;
    private javax.swing.JButton ViewTripsButton1;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox busNoCBox;
    private javax.swing.JComboBox dayCBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox locationFromComboBox;
    private javax.swing.JComboBox locationToComboBox;
    private javax.swing.JComboBox monthCBox;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField priceText;
    private javax.swing.JFormattedTextField timeText;
    private javax.swing.JComboBox tripVenueComboBox;
    private javax.swing.JButton updateTripButton;
    private javax.swing.JComboBox yearCBox;
    // End of variables declaration//GEN-END:variables
}
