package UI;

import RegistryManagement.*;
import BookingManagement.*;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author james
 */
public class ViewTripMenu extends javax.swing.JFrame {

    private Registry reg = Registry.getInstance();
    private List<Trip> tripList;
    private Trip trip;
    private DefaultTableModel tripsTableModel = new DefaultTableModel(new String[]{"Reference No.", "Route", "Schedule", "Bus No."}, 0);
    private SearchEngine search = new SearchEngine();
    private SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
    /**
     * Creates new form ViewTripMenu
     */
    public ViewTripMenu() {
        initComponents();
        
        tripListTable.setModel(tripsTableModel);
        tripList = (List<Trip>) search.searchAvailableTrips();
        for (Trip trip1 : tripList) {
            String route = trip1.getTripFrom()+" to "+trip1.getTripTo();
            tripsTableModel.addRow(new Object[]{ trip1.getReferenceNo(), route, df.format(trip1.getSchedule()),  trip1.getBus().getBusNumber()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editTripButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tripListTable = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editTripButton.setText("Edit Trip");
        editTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTripButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        tripListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tripListTable);
        DefaultTableCellRenderer centerRenderer= new DefaultTableCellRenderer();
        DefaultTableCellRenderer leftRenderer= new DefaultTableCellRenderer();
        DefaultTableCellRenderer rightRenderer= new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        leftRenderer.setHorizontalAlignment (SwingConstants.LEFT);
        rightRenderer.setHorizontalAlignment (SwingConstants.RIGHT);
        tripListTable.setRowSelectionAllowed (true);
        tripListTable.setSelectionMode (ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tripListTable.setEnabled (true);
        tripListTable.setSelectionBackground (java.awt.Color.GRAY);
        tripListTable.setModel(new DefaultTableModel());
        tripList = (List<Trip>)search.searchAvailableTrips();
        for (int c = 0; c < tripListTable.getColumnCount(); c++)
        {
            Class<?> col_class = tripListTable.getColumnClass(c);
            tripListTable.setDefaultEditor(col_class, null);        // remove editor
        }

        removeButton.setText("Remove Trip");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editTripButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTripButton)
                    .addComponent(BackButton)
                    .addComponent(removeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void editTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTripButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tripListTable.getSelectedRow();
        AddTripFrame editTrip = new AddTripFrame();
        if (tripListTable.getSelectedRow() >= 0) {
            String refNo = (String) tripListTable.getValueAt(selectedRow, 0);
            trip = (Trip) search.searchByRefNo(refNo);
            editTrip.loadData(trip);
            editTrip.show();
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row before!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editTripButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        int row = tripListTable.getSelectedRow();
        String refNo = (String) tripListTable.getModel().getValueAt(row, 0);
        trip = (Trip) search.searchByRefNo(refNo);
        if(trip!=null){
            reg.removeTrip(trip);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTripMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTripMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTripMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTripMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTripMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton editTripButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeButton;
    private javax.swing.JTable tripListTable;
    // End of variables declaration//GEN-END:variables
}
